"""phase 2 demand budget workflow

Revision ID: e06cb14076a4
Revises: 0839c53ef635
Create Date: 2026-09-23 09:56:33.473752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06cb14076a4'
down_revision: Union[str, Sequence[str], None] = '0839c53ef635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('term_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('feeding_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'term_no', name='uq_term')
    )
    op.create_table('funding_sources',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('workflow_instances',
    sa.Column('definition', sa.String(length=60), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_ref', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('scope_org_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('stage_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'approved', 'rejected', 'returned', 'cancelled', name='instancestatus', native_enum=False, length=16), nullable=False),
    sa.Column('initiator_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_instances_definition'), ['definition'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_instances_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_instances_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_instances_scope_org_id'), ['scope_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_instances_status'), ['status'], unique=False)

    op.create_table('budget_lines',
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('funding_source_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('alert_threshold_pct', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['funding_source_id'], ['funding_sources.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_lines_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_budget_lines_org_id'), ['org_id'], unique=False)

    op.create_table('menus',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'retired', name='menustatus', native_enum=False, length=16), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_actions',
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('stage_key', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_actions_instance_id'), ['instance_id'], unique=False)

    op.create_table('budget_exceptions',
    sa.Column('budget_line_id', sa.Uuid(), nullable=False),
    sa.Column('source_entity', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source_ref', sa.String(length=60), nullable=False),
    sa.Column('requested_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('shortfall', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='exceptionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_exceptions_budget_line_id'), ['budget_line_id'], unique=False)

    op.create_table('menu_days',
    sa.Column('menu_id', sa.Uuid(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('dish', sa.String(length=200), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_menu_days_menu_id'), ['menu_id'], unique=False)

    op.create_table('procurement_plans',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('county_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('budget_line_id', sa.Uuid(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'returned', 'rejected', 'sourcing', 'closed', name='planstatus', native_enum=False, length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['county_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procurement_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procurement_plans_county_id'), ['county_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_procurement_plans_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_procurement_plans_status'), ['status'], unique=False)

    op.create_table('budget_commitments',
    sa.Column('budget_line_id', sa.Uuid(), nullable=False),
    sa.Column('source_entity', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source_ref', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.Enum('held', 'invoiced', 'paid', 'released', name='commitmentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('exception_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['budget_exceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_commitments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_commitments_budget_line_id'), ['budget_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_commitments_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_commitments_status'), ['status'], unique=False)

    op.create_table('plan_lines',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('lot', sa.String(length=80), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('schools', sa.JSON(), nullable=False),
    sa.Column('delivery_window', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['procurement_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_lines_plan_id'), ['plan_id'], unique=False)

    op.create_table('school_demands',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('county_id', sa.Uuid(), nullable=True),
    sa.Column('term_id', sa.Uuid(), nullable=False),
    sa.Column('menu_id', sa.Uuid(), nullable=True),
    sa.Column('enrolment', sa.Integer(), nullable=False),
    sa.Column('attendance_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('feeding_days', sa.Integer(), nullable=False),
    sa.Column('wastage_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('storage_capacity_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('preferred_delivery', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('nutrition', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'validated', 'approved', 'returned', 'converted', 'closed', name='demandstatus', native_enum=False, length=16), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['procurement_plans.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'term_id', name='uq_demand_school_term')
    )
    with op.batch_alter_table('school_demands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_demands_county_id'), ['county_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_demands_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_school_demands_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_demands_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_demands_term_id'), ['term_id'], unique=False)

    op.create_table('demand_lines',
    sa.Column('demand_id', sa.Uuid(), nullable=False),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('grams_per_learner_cycle', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gross_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('override_qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('override_reason', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['school_demands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demand_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_lines_demand_id'), ['demand_id'], unique=False)

    with op.batch_alter_table('commodities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_price', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commodities', schema=None) as batch_op:
        batch_op.drop_column('reference_price')

    with op.batch_alter_table('demand_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_lines_demand_id'))

    op.drop_table('demand_lines')
    with op.batch_alter_table('school_demands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_demands_term_id'))
        batch_op.drop_index(batch_op.f('ix_school_demands_status'))
        batch_op.drop_index(batch_op.f('ix_school_demands_school_id'))
        batch_op.drop_index(batch_op.f('ix_school_demands_reference'))
        batch_op.drop_index(batch_op.f('ix_school_demands_county_id'))

    op.drop_table('school_demands')
    with op.batch_alter_table('plan_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_lines_plan_id'))

    op.drop_table('plan_lines')
    with op.batch_alter_table('budget_commitments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_commitments_status'))
        batch_op.drop_index(batch_op.f('ix_budget_commitments_source_id'))
        batch_op.drop_index(batch_op.f('ix_budget_commitments_budget_line_id'))

    op.drop_table('budget_commitments')
    with op.batch_alter_table('procurement_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurement_plans_status'))
        batch_op.drop_index(batch_op.f('ix_procurement_plans_reference'))
        batch_op.drop_index(batch_op.f('ix_procurement_plans_county_id'))

    op.drop_table('procurement_plans')
    with op.batch_alter_table('menu_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_menu_days_menu_id'))

    op.drop_table('menu_days')
    with op.batch_alter_table('budget_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_exceptions_budget_line_id'))

    op.drop_table('budget_exceptions')
    with op.batch_alter_table('workflow_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_actions_instance_id'))

    op.drop_table('workflow_actions')
    op.drop_table('menus')
    with op.batch_alter_table('budget_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_lines_org_id'))
        batch_op.drop_index(batch_op.f('ix_budget_lines_code'))

    op.drop_table('budget_lines')
    with op.batch_alter_table('workflow_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_instances_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_instances_scope_org_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_instances_entity_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_instances_entity'))
        batch_op.drop_index(batch_op.f('ix_workflow_instances_definition'))

    op.drop_table('workflow_instances')
    op.drop_table('funding_sources')
    op.drop_table('academic_terms')
    # ### end Alembic commands ###
