"""phase 3 e-procurement

Revision ID: 592e64cc2773
Revises: e06cb14076a4
Create Date: 2026-09-23 10:34:55.037095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592e64cc2773'
down_revision: Union[str, Sequence[str], None] = 'e06cb14076a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


CRITERIA = '[{"key": "technical", "label": "Technical compliance", "max": 20, "auto": false}, {"key": "capacity", "label": "Capacity to supply", "max": 15, "auto": false}, {"key": "quality", "label": "Quality & food safety", "max": 10, "auto": false}, {"key": "local", "label": "Local sourcing / distance", "max": 10, "auto": false}, {"key": "inclusion", "label": "Inclusion (verified women/youth/PWD-led)", "max": 5, "auto": true}]'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('bids',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'withdrawn', 'opened', 'awarded', 'unsuccessful', name='bidstatus', native_enum=False, length=16), nullable=False),
    sa.Column('sealed_payload', sa.Text(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_payload', sa.JSON(), nullable=True),
    sa.Column('lots_bid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['procurement_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'supplier_id', name='uq_bid_supplier_event')
    )
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('clarifications',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('answered_by', sa.Uuid(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['procurement_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clarifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clarifications_event_id'), ['event_id'], unique=False)

    op.create_table('contracts',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('county_id', sa.Uuid(), nullable=True),
    sa.Column('budget_line_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('purchase', 'framework', name='contractkind', native_enum=False, length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'expired', 'terminated', name='contractstatus', native_enum=False, length=16), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['budget_line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['county_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['procurement_events.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_county_id'), ['county_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('evaluation_assignments',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('coi_declared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('coi_statement', sa.Text(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['procurement_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uq_eval_user')
    )
    with op.batch_alter_table('evaluation_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_assignments_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluation_assignments_user_id'), ['user_id'], unique=False)

    op.create_table('procurement_lots',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('lot_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('specification', sa.Text(), nullable=False),
    sa.Column('delivery_window', sa.String(length=160), nullable=False),
    sa.Column('schools', sa.JSON(), nullable=False),
    sa.Column('plan_line_id', sa.Uuid(), nullable=True),
    sa.Column('estimated_unit_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['procurement_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procurement_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procurement_lots_event_id'), ['event_id'], unique=False)

    op.create_table('awards',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('bid_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'approved', 'cancelled', name='awardstatus', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['procurement_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['procurement_lots.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_awards_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_awards_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('contract_lines',
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('lot_id', sa.Uuid(), nullable=False),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lot_id'], ['procurement_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_lines_contract_id'), ['contract_id'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('county_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('issued', 'acknowledged', 'partially_fulfilled', 'fulfilled', 'cancelled', name='postatus', native_enum=False, length=24), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('delivery_window', sa.String(length=160), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['county_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_county_id'), ['county_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('po_lines',
    sa.Column('po_id', sa.Uuid(), nullable=False),
    sa.Column('contract_line_id', sa.Uuid(), nullable=False),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('schools', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contract_line_id'], ['contract_lines.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('po_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_po_lines_po_id'), ['po_id'], unique=False)

    with op.batch_alter_table('procurement_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('clarification_deadline', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('technical_weight', sa.Integer(), nullable=False, server_default='60'))
        batch_op.add_column(sa.Column('financial_weight', sa.Integer(), nullable=False, server_default='40'))
        batch_op.add_column(sa.Column('criteria', sa.JSON(), nullable=False, server_default=sa.text("'" + CRITERIA + "'")))
        batch_op.add_column(sa.Column('required_docs', sa.JSON(), nullable=False, server_default=sa.text("'[\"registration\", \"bank\"]'")))
        batch_op.add_column(sa.Column('contract_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('contract_end', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('opened_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('results', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
        batch_op.alter_column('awarded_to',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_procurement_events_plan_id'), ['plan_id'], unique=False)
        batch_op.create_foreign_key('fk_procurement_events_plan_id', 'procurement_plans', ['plan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procurement_events', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_procurement_events_plan_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_procurement_events_plan_id'))
        batch_op.alter_column('awarded_to',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('results')
        batch_op.drop_column('opened_by')
        batch_op.drop_column('opened_at')
        batch_op.drop_column('contract_end')
        batch_op.drop_column('contract_start')
        batch_op.drop_column('required_docs')
        batch_op.drop_column('criteria')
        batch_op.drop_column('financial_weight')
        batch_op.drop_column('technical_weight')
        batch_op.drop_column('clarification_deadline')
        batch_op.drop_column('plan_id')

    with op.batch_alter_table('po_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_po_lines_po_id'))

    op.drop_table('po_lines')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_reference'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_county_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_contract_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('contract_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_lines_contract_id'))

    op.drop_table('contract_lines')
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_awards_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_awards_event_id'))

    op.drop_table('awards')
    with op.batch_alter_table('procurement_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurement_lots_event_id'))

    op.drop_table('procurement_lots')
    with op.batch_alter_table('evaluation_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_evaluation_assignments_event_id'))

    op.drop_table('evaluation_assignments')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_reference'))
        batch_op.drop_index(batch_op.f('ix_contracts_event_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_county_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('clarifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clarifications_event_id'))

    op.drop_table('clarifications')
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_bids_event_id'))

    op.drop_table('bids')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
