"""Phase 4: aggregation, quality, inventory, logistics, e-POD, exceptions

Revision ID: 722c9befe580
Revises: 592e64cc2773
Create Date: 2026-09-23 11:09:02.786836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722c9befe580'
down_revision: Union[str, Sequence[str], None] = '592e64cc2773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_counts',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_counts_location_id'), ['location_id'], unique=False)

    op.create_table('exception_cases',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_ref', sa.String(length=60), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('owner_role', sa.String(length=60), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='casestatus', native_enum=False, length=24), nullable=False),
    sa.Column('corrective_action', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exception_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exception_cases_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_exception_cases_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exception_cases_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_exception_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_exception_cases_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('batches',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('po_id', sa.Uuid(), nullable=True),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('variety', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('intake_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('accepted_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rejected_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('production_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'awaiting_inspection', 'cleared', 'rejected', 'depleted', name='batchstatus', native_enum=False, length=24), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_batches_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('dispatches',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('po_id', sa.Uuid(), nullable=False),
    sa.Column('source_location_id', sa.Uuid(), nullable=False),
    sa.Column('county_id', sa.Uuid(), nullable=True),
    sa.Column('vehicle', sa.String(length=40), nullable=False),
    sa.Column('driver_user_id', sa.Uuid(), nullable=True),
    sa.Column('driver_name', sa.String(length=120), nullable=False),
    sa.Column('driver_phone', sa.String(length=20), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'dispatched', 'in_transit', 'delivered', 'closed', 'cancelled', name='dispatchstatus', native_enum=False, length=24), nullable=False),
    sa.Column('milestones', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatches_county_id'), ['county_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_driver_user_id'), ['driver_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_dispatches_source_location_id'), ['source_location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatches_status'), ['status'], unique=False)

    op.create_table('dispatch_lines',
    sa.Column('dispatch_id', sa.Uuid(), nullable=False),
    sa.Column('po_line_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('delivered_qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('accepted_qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rejected_qty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rejection_reason', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispatch_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_lines_dispatch_id'), ['dispatch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_lines_school_id'), ['school_id'], unique=False)

    op.create_table('intakes',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('producer_name', sa.String(length=160), nullable=False),
    sa.Column('producer_phone', sa.String(length=20), nullable=False),
    sa.Column('producer_group', sa.String(length=160), nullable=False),
    sa.Column('producer_gender', sa.String(length=16), nullable=False),
    sa.Column('producer_youth', sa.Boolean(), nullable=True),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('variety', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source_location', sa.String(length=160), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_ref')
    )
    with op.batch_alter_table('intakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intakes_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intakes_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intakes_reference'), ['reference'], unique=True)

    op.create_table('proofs_of_delivery',
    sa.Column('dispatch_id', sa.Uuid(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_user_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_name', sa.String(length=160), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('condition', sa.String(length=24), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('signature_key', sa.String(length=300), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('captured_offline', sa.Boolean(), nullable=False),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.id'], ),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_ref')
    )
    with op.batch_alter_table('proofs_of_delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proofs_of_delivery_dispatch_id'), ['dispatch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proofs_of_delivery_school_id'), ['school_id'], unique=False)

    op.create_table('quality_inspections',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('inspector_id', sa.Uuid(), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('result', sa.Enum('accepted', 'partially_accepted', 'downgraded', 'rejected', name='inspectionresult', native_enum=False, length=24), nullable=False),
    sa.Column('accepted_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('rejected_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('corrective_action', sa.Text(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('captured_offline', sa.Boolean(), nullable=False),
    sa.Column('client_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_ref')
    )
    with op.batch_alter_table('quality_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_inspections_batch_id'), ['batch_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('type', sa.Enum('receipt', 'issue', 'transfer_in', 'transfer_out', 'adjustment', 'return_', 'waste', name='movementtype', native_enum=False, length=24), nullable=False),
    sa.Column('status', sa.Enum('posted', 'pending_approval', 'rejected', name='movementstatus', native_enum=False, length=24), nullable=False),
    sa.Column('source_entity', sa.String(length=40), nullable=False),
    sa.Column('source_ref', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_commodity_code'), ['commodity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_status'), ['status'], unique=False)

    with op.batch_alter_table('po_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispatched_qty', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('accepted_qty', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('rejected_qty', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('po_lines', schema=None) as batch_op:
        batch_op.drop_column('rejected_qty')
        batch_op.drop_column('accepted_qty')
        batch_op.drop_column('dispatched_qty')

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_status'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_location_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_commodity_code'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_batch_id'))
        batch_op.drop_index(batch_op.f('ix_stock_movements_at'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('quality_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_inspections_batch_id'))

    op.drop_table('quality_inspections')
    with op.batch_alter_table('proofs_of_delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proofs_of_delivery_school_id'))
        batch_op.drop_index(batch_op.f('ix_proofs_of_delivery_dispatch_id'))

    op.drop_table('proofs_of_delivery')
    with op.batch_alter_table('intakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intakes_reference'))
        batch_op.drop_index(batch_op.f('ix_intakes_location_id'))
        batch_op.drop_index(batch_op.f('ix_intakes_batch_id'))

    op.drop_table('intakes')
    with op.batch_alter_table('dispatch_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_lines_school_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_lines_dispatch_id'))

    op.drop_table('dispatch_lines')
    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatches_status'))
        batch_op.drop_index(batch_op.f('ix_dispatches_source_location_id'))
        batch_op.drop_index(batch_op.f('ix_dispatches_reference'))
        batch_op.drop_index(batch_op.f('ix_dispatches_po_id'))
        batch_op.drop_index(batch_op.f('ix_dispatches_driver_user_id'))
        batch_op.drop_index(batch_op.f('ix_dispatches_county_id'))

    op.drop_table('dispatches')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_batches_status'))
        batch_op.drop_index(batch_op.f('ix_batches_po_id'))
        batch_op.drop_index(batch_op.f('ix_batches_location_id'))
        batch_op.drop_index(batch_op.f('ix_batches_code'))

    op.drop_table('batches')
    with op.batch_alter_table('exception_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exception_cases_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_exception_cases_status'))
        batch_op.drop_index(batch_op.f('ix_exception_cases_reference'))
        batch_op.drop_index(batch_op.f('ix_exception_cases_org_id'))
        batch_op.drop_index(batch_op.f('ix_exception_cases_category'))

    op.drop_table('exception_cases')
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_counts_location_id'))

    op.drop_table('stock_counts')
    # ### end Alembic commands ###
