"""Phase 5: invoices, three-way match, payments, complaints, movement metadata

Revision ID: 7722da78f60e
Revises: 722c9befe580
Create Date: 2026-09-23 11:45:56.816532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7722da78f60e'
down_revision: Union[str, Sequence[str], None] = '722c9befe580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaints',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('school_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('entity_ref', sa.String(length=60), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'investigating', 'resolved', 'closed', name='complaintstatus', native_enum=False, length=24), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('satisfaction', sa.Integer(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('invoices',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('supplier_invoice_no', sa.String(length=60), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('po_id', sa.Uuid(), nullable=False),
    sa.Column('contract_id', sa.Uuid(), nullable=False),
    sa.Column('county_id', sa.Uuid(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'verified', 'approved', 'partially_paid', 'paid', 'returned', 'rejected', 'cancelled', name='invoicestatus', native_enum=False, length=24), nullable=False),
    sa.Column('match', sa.JSON(), nullable=False),
    sa.Column('document_key', sa.String(length=300), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['county_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_county_id'), ['county_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('invoice_lines',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('po_line_id', sa.Uuid(), nullable=False),
    sa.Column('commodity_code', sa.String(length=40), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['po_line_id'], ['po_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_lines_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_lines_po_line_id'), ['po_line_id'], unique=False)

    op.create_table('payments',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('transaction_ref', sa.String(length=80), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'reversed', name='paymentstatus', native_enum=False, length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_supplier_id'), ['supplier_id'], unique=False)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_column('meta')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_payments_reference'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_lines_po_line_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_lines_invoice_id'))

    op.drop_table('invoice_lines')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_reference'))
        batch_op.drop_index(batch_op.f('ix_invoices_po_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_county_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_contract_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_reference'))
        batch_op.drop_index(batch_op.f('ix_complaints_org_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_category'))

    op.drop_table('complaints')
    # ### end Alembic commands ###
