"""Phase 6: recall, routes, payment details, integration log

Revision ID: 59255368db93
Revises: 7722da78f60e
Create Date: 2026-09-23 12:06:53.213733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59255368db93'
down_revision: Union[str, Sequence[str], None] = '7722da78f60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_transactions',
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('system', sa.String(length=20), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('county_id', sa.Uuid(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('file_key', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integration_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_transactions_county_id'), ['county_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integration_transactions_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_integration_transactions_system'), ['system'], unique=False)

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recalled_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('recall_reason', sa.Text(), server_default='', nullable=False))

    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route', sa.JSON(), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_details', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('payment_details_pending', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_column('payment_details_pending')
        batch_op.drop_column('payment_details')

    with op.batch_alter_table('dispatches', schema=None) as batch_op:
        batch_op.drop_column('route')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_column('recall_reason')
        batch_op.drop_column('recalled_at')

    with op.batch_alter_table('integration_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_transactions_system'))
        batch_op.drop_index(batch_op.f('ix_integration_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_integration_transactions_county_id'))

    op.drop_table('integration_transactions')
    # ### end Alembic commands ###
