"""Phase 7: SMS/email outbox

Revision ID: 3ff9af448460
Revises: 59255368db93
Create Date: 2026-09-23 12:51:50.378918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff9af448460'
down_revision: Union[str, Sequence[str], None] = '59255368db93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_messages',
    sa.Column('channel', sa.String(length=8), nullable=False),
    sa.Column('to', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_messages_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbound_messages_status'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_next_attempt_at'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_channel'))

    op.drop_table('outbound_messages')
    # ### end Alembic commands ###
