import type { WF } from "@/components/Workflow";

export type MatchLine = { po_line_id: string; commodity_code: string; unit: string; ordered_qty: string; po_price: string; accepted_qty: string;
  previously_invoiced: string; invoiced_qty: string; invoiced_price: string; result: string; issues: string[] };
export type Invoice = { id: string; reference: string; supplier_invoice_no: string; supplier: string; po_id: string; po: string; invoice_date: string;
  subtotal: number; tax_amount: number; total: number; paid_amount: number; balance: number; status: string; match_result: string | null;
  submitted_at: string; approved_at: string | null; paid_at: string | null; days_to_pay: number | null; has_document: boolean;
  lines?: { id: string; po_line_id: string; commodity: string; unit: string; quantity: number; unit_price: number; amount: number }[];
  match?: { result: string; tolerance_pct: number; checked_at: string; verified_by?: string; lines: MatchLine[] }; notes?: string;
  payments?: { id: string; reference: string; amount: number; method: string; transaction_ref: string; paid_on: string; status: string; note: string }[];
  workflow?: WF | null; can_pay?: boolean; why_not_pay?: string };
export type Billable = { id: string; reference: string; supplier: string; status: string; billable_value: number;
  lines: { po_line_id: string; commodity: string; unit: string; ordered_qty: number; accepted_qty: number; rejected_qty: number; invoiced_qty: number;
    billable_qty: number; unit_price: number }[] };
export type PaymentRow = { id: string; reference: string; invoice_id: string; invoice: string; supplier: string; amount: number; method: string;
  transaction_ref: string; paid_on: string; status: string };
export type Complaint = { id: string; reference: string; channel: string; category: string; category_label: string; priority: string; subject: string;
  description: string; county: string | null; school: string | null; supplier: string | null; supplier_id: string | null; entity_ref: string;
  submitted_by: string; contact: string; status: string; assigned_to: string | null; due_at: string | null; overdue: boolean; resolution: string;
  resolved_at: string | null; satisfaction: number | null; history: { at: string; by: string; action: string; note: string }[]; created_at: string;
  actions?: string[] };
export type Scorecard = { supplier_id: string; supplier: string; supplier_type: string; inclusion: string | null; orders: number; deliveries: number;
  on_time_deliveries: number; ordered_qty: number; accepted_qty: number; delivered_qty: number; complaints: number; open_complaints: number;
  avg_days_to_pay: number | null; rates: Record<"on_time" | "acceptance" | "fill" | "inspection" | "complaints", number | null>;
  weights: Record<string, number>; score: number | null; band: string | null;
  recent_deliveries?: { dispatch: string; school: string; planned: string; received_at: string; status: string; on_time: boolean }[];
  recent_complaints?: { reference: string; category: string; subject: string; status: string; created_at: string }[] };
export const METHODS: Record<string, string> = { bank: "Bank transfer (EFT/RTGS)", mpesa: "M-Pesa", cheque: "Cheque", ifmis: "IFMIS" };
export const pct = (n: number | null | undefined) => (n == null ? "—" : `${Number(n).toFixed(0)}%`);
