export type Loc = { id: string; name: string; code: string; type: string; parent_id: string | null };
export type Intake = { id: string; reference: string; producer_name: string; producer_phone: string; producer_group: string; producer_gender: string;
  producer_youth: boolean | null; commodity_code: string; variety: string; quantity: number; unit: string; source_location: string; received_at: string };
export type Check = { param: string; value: number | boolean | null; limit: number | boolean; rule: string; pass: boolean | null };
export type Inspection = { id: string; inspector: string; inspected_at: string; parameters: Record<string, unknown>; checks: Check[]; grade: string; result: string;
  accepted_qty: number; rejected_qty: number; reason: string; corrective_action: string; photos: string[]; captured_offline: boolean };
export type Batch = { id: string; code: string; location_id: string; location: string; supplier: string | null; commodity_code: string; commodity: string;
  variety: string; unit: string; intake_qty: number; accepted_qty: number; rejected_qty: number; grade: string; expiry_date: string | null; status: string;
  intake_count: number; created_at: string; on_hand: number; intakes?: Intake[]; inspections?: Inspection[]; quality_spec?: Record<string, number>;
  can_inspect?: boolean; why_not_inspect?: string };
export type Balance = { location_id: string; location: string; location_type: string; batch_id: string | null; batch_code: string | null; grade: string;
  expiry_date: string | null; commodity_code: string; commodity: string; unit: string; on_hand: number; pending_adjustment: number; alerts: string[] };
export type Movement = { id: string; at: string; location: string; batch_code: string | null; commodity_code: string; unit: string; quantity: number; type: string;
  status: string; source_entity: string; source_ref: string; reason: string; by: string; workflow_id?: string };
export type DLine = { id: string; po_line_id: string; commodity_code: string; commodity: string; unit: string; batch_id: string | null; batch_code: string | null;
  quantity: number; delivered_qty: number | null; accepted_qty: number | null; rejected_qty: number | null; rejection_reason: string };
export type Stop = { school_id: string; school: string; lines: DLine[]; pod: null | { id: string; receiver_name: string; received_at: string; condition: string;
  remarks: string; status: string; signature_key: string; photos: string[]; captured_offline: boolean } };
export type Milestone = { status: string; at: string; by: string; note: string; school?: string; lat?: number; lng?: number };
export type Dispatch = { id: string; reference: string; po_id: string; po: string; supplier: string; source_location_id: string; source: string; vehicle: string;
  driver_user_id: string | null; driver_name: string; driver_phone: string; planned_date: string; status: string; milestones: Milestone[]; stops: Stop[];
  total_qty: number; created_at: string; can_confirm?: string[]; can_drive?: boolean; can_dispatch?: boolean };
export type Case = { id: string; reference: string; category: string; severity: string; entity: string; entity_id: string; entity_ref: string; org: string | null;
  supplier: string | null; title: string; detail: string; owner_role: string; due_at: string | null; overdue: boolean; status: string;
  corrective_action: string; resolution: string; resolved_by: string | null; resolved_at: string | null; created_at: string };
export const fileUrl = (key: string) => `/api/v1/fulfilment/files/${key}`;
